CREATE TABLE MARCA
(
  id_marca INT IDENTITY NOT NULL,
  descripcion VARCHAR(50) NOT NULL,
  estado INT NOT NULL,
  CONSTRAINT PK_id_marca PRIMARY KEY (id_marca)
);

CREATE TABLE CATEGORIA
(
  descripcion VARCHAR(50) NOT NULL,
  id_categoria INT IDENTITY NOT NULL,
  estado INT NOT NULL,
  CONSTRAINT PK_id_categoria PRIMARY KEY (id_categoria)
);

CREATE TABLE ROL
(
  id_rol INT IDENTITY NOT NULL,
  descripcion VARCHAR(50) NOT NULL,
  CONSTRAINT PK_id_rol PRIMARY KEY (id_rol)
);

CREATE TABLE PROVINCIA
(
  id_provincia INT IDENTITY NOT NULL,
  nomb_prov VARCHAR(50) NOT NULL,
  CONSTRAINT PK_id_provincia PRIMARY KEY (id_provincia)
);

CREATE TABLE CIUDAD
(
  id_ciudad INT IDENTITY NOT NULL,
  nomb_ciudad VARCHAR(50) NOT NULL,
  cod_postal INT NOT NULL,
  id_provincia INT NOT NULL,
  CONSTRAINT PK_id_ciudad PRIMARY KEY (id_ciudad),
  CONSTRAINT FK_CIUDAD_id_provincia FOREIGN KEY (id_provincia) REFERENCES PROVINCIA(id_provincia) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE Direccion
(
  id_direccion INT IDENTITY NOT NULL,
  calle VARCHAR(50) NOT NULL,
  altura INT NOT NULL,
  estado INT NOT NULL,
  id_ciudad INT NOT NULL,
  CONSTRAINT PK_id_direccion PRIMARY KEY (id_direccion),
  CONSTRAINT FK_Direccion_id_ciudad FOREIGN KEY (id_ciudad) REFERENCES CIUDAD(id_ciudad) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE USUARIO
(
  dni INT NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  nombre VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  nro_telefono VARCHAR(50) NOT NULL,
  estado INT NOT NULL,
  id_rol INT NOT NULL,
  id_direccion INT NOT NULL,
  CONSTRAINT PK_dni PRIMARY KEY (dni),
  CONSTRAINT UQ_email UNIQUE (email),
  CONSTRAINT FK_USUARIO_id_rol FOREIGN KEY (id_rol) REFERENCES ROL(id_rol) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT FK_USUARIO_id_direccion FOREIGN KEY (id_direccion) REFERENCES Direccion(id_direccion) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE PRODUCTO
(
  id_producto INT IDENTITY NOT NULL,
  nombre VARCHAR(50) NOT NULL,
  precio FLOAT NOT NULL,
  stock INT NOT NULL,
  descripcion VARCHAR(50) NOT NULL,
  estado INT NOT NULL,
  id_marca INT NOT NULL,
  id_categoria INT NOT NULL,
  dni INT NOT NULL,
  CONSTRAINT PK_id_producto PRIMARY KEY (id_producto),
  CONSTRAINT FK_PRODUCTO_id_marca FOREIGN KEY (id_marca) REFERENCES MARCA(id_marca) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT FK_PRODUCTO_id_categoria FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT FK_PRODUCTO_dni FOREIGN KEY (dni) REFERENCES USUARIO(dni) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE IMAGEN
(
  id_imagen INT IDENTITY NOT NULL,
  ruta_archivo VARCHAR(100) NOT NULL,
  id_producto INT NOT NULL,
  CONSTRAINT PK_id_imagen PRIMARY KEY (id_imagen),
  CONSTRAINT FK_IMAGEN_id_producto FOREIGN KEY (id_producto) REFERENCES PRODUCTO(id_producto) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE VENTA
(
  id_venta INT IDENTITY NOT NULL,
  estado VARCHAR(50) NOT NULL,
  domicilio_entrega VARCHAR(150) NOT NULL,
  total INT NOT NULL,
  fecha_venta DATE NOT NULL,
  dni INT NOT NULL,
  CONSTRAINT PK_id_venta PRIMARY KEY (id_venta),
  CONSTRAINT FK_VENTA_dni FOREIGN KEY (dni) REFERENCES USUARIO(dni) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE VENTA_DETALLE
(
  id_venta_detalle INT IDENTITY NOT NULL,
  cantidad INT NOT NULL,
  precio_unitario FLOAT NOT NULL,
  subtotal FLOAT NOT NULL,
  id_producto INT NOT NULL,
  id_venta INT NOT NULL,
  CONSTRAINT PK_id_venta_detalle PRIMARY KEY (id_venta_detalle),
  CONSTRAINT FK_VENTA_DETALLE_id_producto FOREIGN KEY (id_producto) REFERENCES PRODUCTO(id_producto) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT FK_VENTA_DETALLE_id_venta FOREIGN KEY (id_venta) REFERENCES VENTA(id_venta) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE METODO_PAGO
(
  id_metodo_pago INT IDENTITY NOT NULL,
  descripcion VARCHAR(50) NOT NULL,
  CONSTRAINT PK_id_metodo_pago PRIMARY KEY (id_metodo_pago)
);

CREATE TABLE VENTA_PAGO
(
  monto FLOAT NOT NULL,
  id_venta INT NOT NULL,
  id_metodo_pago INT NOT NULL,
  CONSTRAINT PK_id_venta_id_metodo_pago PRIMARY KEY (id_venta, id_metodo_pago),
  CONSTRAINT FK_VENTA_PAGO_id_venta FOREIGN KEY (id_venta) REFERENCES VENTA(id_venta) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_VENTA_PAGO_id_metodo_pago FOREIGN KEY (id_metodo_pago) REFERENCES METODO_PAGO(id_metodo_pago) ON DELETE NO ACTION ON UPDATE CASCADE
);
